package net.rizecookey.combatedit.extension;

public interface DefaultAttributeContainerExtensions extends DefaultAttributeContainerCompatibilityExtension, DefaultAttributeContainerInstancesProvider {
}
